### ISSUE TITLE
pyhive.presto example needs JWT_TOKEN support

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/data-platform-demo#19]
**Describe the bug**
The sample code showing how to create a pyhive.preso connection doesn't work.

**To Reproduce**
1. Run the sample notebook.  It will fail very quickly due to other changes made to data commons since last update.
2. Switch to osc_datacommons_dev_auth branch
3. Rerun the sample notebook.  It will succeed in making the initial trino connection because it is now updated to handle JWT_TOKEN auth.  However it will still fail when attempting to demonstration the pyhive.presto connection.

**Expected behavior**
The pyhive.presto connection should work.  And the sqlalchemy connection should also be fixed to work.

**Screenshots**

**Additional context**

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC  one theory I had was that I corrupted my python deps by installing *both* `sqlalchemy-trino` and `pyhive[trino]`.  So one experiment would be to make sure `sqlalchemy-trino` is *not* installed, but only `pyhive[trino]`, or `pyhive[presto,trino]`  and seeing if that works.

**Comment by erikerlandson** [comment]
We have sqlalchemy working without pyhive.presto (using sqlalchemy-trino instead)
