### ISSUE TITLE
trino-iceberg-demo fails due to partitioning declaration on CL2 DEV cluster

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/data-platform-demo#49]
**Describe the bug**
When I attempt to run Cell 7, I get this error message as a result of trying to execute this sql statement:

```
create table if not exists osc_datacommons_dev.sandbox.trino_iceberg_demo(
    quarter varchar,
    reduction double
) with (
    format = 'ORC',
    partitioning = array['quarter']
)
```

`TrinoUserError: TrinoUserError(type=USER_ERROR, name=INVALID_TABLE_PROPERTY, message="Catalog 'osc_datacommons_dev' does not support table property 'partitioning'", query_id=20220319_141301_00002_thkmy)`

**To Reproduce**
1. Start with Jupiter Notebook: https://jupyterhub-odh-jupyterhub.apps.odh-cl2.apps.os-climate.org/user/michaeltiemannosc/lab/tree/data-platform-demo/notebooks/trino-iceberg-demo.ipynb
2. pip install all prerequisites
3. ingest_catalog='osc_datacommons_dev'
4. ingest_schema='sandbox`
5. run notebook
6. See error when attempting to execute this code:

```
import osc_ingest_trino as osc
columnschema = osc.create_table_schema_pairs(df1)

tabledef = f"""
create table if not exists {ingest_catalog}.{ingest_schema}.{ingest_table}(
{columnschema}
) with (
    format = 'ORC',
    partitioning = array['quarter']
)
"""
print(tabledef)
qres = engine.execute(tabledef)
print(qres.fetchall())
```

**Expected behavior**
I expected the notebook would create a proper table for the iceberg world that is the CL2 dev cluster.

**Screenshots**

**Additional context**

**Comment by caldeirav** [comment]
These are the only 3 properties we should have:

format | Optionally specifies the format of table data files; either PARQUET or ORC. Defaults to ORC
partitioning | Optionally specifies table partitioning. If a table is partitioned by columns c1 and c2, the partitioning property would be partitioning = ARRAY['c1', 'c2']
location | Optionally specifies the file system location URI for the table

**Comment by HumairAK** [comment]
Err yeah, seems I used the wrong connector. 

Comparison: 
1) iceberg catalog in osc-cl1: [link](https://github.com/operate-first/apps/blob/master/kfdefs/overlays/osc/osc-cl1/trino/configs/catalogs/osc_datacommons_iceberg_dev.properties) 
2) catalog in osc-cl2: [link](https://github.com/operate-first/apps/blob/master/kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties)

Notice: `connector.name=hive-hadoop2` in the latter. Will change to iceberg. 

To clarify we also want the following right? 
```
iceberg.file-format=PARQUET
iceberg.compression-codec=GZIP
iceberg.max-partitions-per-writer=100
```

**Comment by HumairAK** [comment]
https://github.com/operate-first/apps/pull/1768

**Comment by caldeirav** [comment]
These are the general configuration properties, the ones i highlighted are only table properties and there are only 3 of them based on latest documentation: https://trino.io/docs/current/connector/iceberg.html

**Comment by HumairAK** [comment]
Yes, since the connector is not iceberg the first thing is to deploy it as such, so these table properties can be supported. Above I'm essentially asking if the configuration should emulate osc-cl1 iceberg catalog deployment exactly.

**Comment by MichaelTiemannOSC** [comment]
Success!  Closing...
