### ISSUE TITLE
Onboard WRI Powerplant data

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/data-platform-demo#5]
**Is your feature request related to a problem? Please describe.**
The WRI PowerPlant Dataset needs to be onboarded to the Red Hat data platform.  It is available at this S3 bucket location: s3://dev-osc-physical-landing-309737258120/datacommon-physicalrisk-landing/wri-pp/wri-pp.tsv

The is the original WRI data, which means it has not been enhanced with LEI matching information.  But it's very much a first step to demonstrating what metadata, ETL processes, etc., are needed to load tabular data that our tools will use.

**Describe the solution you'd like**
We want to see a complete, agreed set of steps (and supporting code) so that we know what a proper onboarding of such data will entail.  We can then adapt those processes to onboarding other data, such as PUDL (which has its own complexities and extra goodness).

**Describe alternatives you've considered**
We have previously asked to onboard PUDL data, but the WRI data might be a better first step--it's only a single TSV file, not a combination of Parquet and SQLITE databases.

**Additional context**
The WRI data is not tidy, in that each row has multiple time-based observations.  We don't necessarily need to correct that for ingest, but we should consider the question of when and where to renormalize the data into a series of tables: fundamental power plant data, and then operational data (by year) and estimated data.

**Comment by MichaelTiemannOSC** [comment]
We now have the data available in a demo bucket: s3://ocp-odh-os-demo-s3/data/WRI-upload/wri-pp.tsv

The next step of the process is the proper ETL of the data and proper documentation of how the Physical Risk team will access this data.  This can be done before or after we stand up the repository/project for the Physical Risk workstream team.

Joe Moorhouse (invited as @joemoorhouse) will work on this from the tool side.  Can @erikerlandson be the counterparty on the Data Commons side to make recommendations about how to honor the data lineage, versioning, metadata, etc.?  Of course the tool can simply slurp in CSV data into a dataframe and be done with it, but this is a chance to highlight the value-add of the data pipeline architecture at the root of the Physical Risk tool.

We can close this issue when we are happy that we have onboarded the data in whatever we consider to be a best-practices way.  We don't need to keep this issue open when the data becomes a data management question.

**Comment by caldeirav** [comment]
Now that we have a base sample for PUDL and we managed to get the security layers working, should we actually create a repository with the proper templating for WRI_ingestion_pipeline and develop the pipeline properly i.e. not as a demo sample?

**Comment by MichaelTiemannOSC** [comment]
That would be great.  The best WRI data is here (where it's supposed to be):

```obj = s3.get_object(
    Bucket=os.environ['S3_BUCKET'],
    Key='WRI/global_power_plant_database_v_1_3/global_power_plant_database.csv'
)
```

The demo notebook WRI-tidy.ipynb has two pandas melt operations which transform the original table into three tables: the fundamental plant data and the two tidy data tables, one for annual generation (in GWh) and the other for estimated generation (in GWh).  I'll start copying in patterns from the pudl ingest and check those changes in.  We should be able to create a proper ingestion file shortly and delete the initial demo file when that's done.

**Comment by MichaelTiemannOSC** [comment]
This is largely complete, with metadata-related issues being resolved in other issues that are much bigger that this item.
